services:

  postgres_new:
    image: pgvector/pgvector:pg16
    container_name: qa_postgres_new
    restart: always

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: qa_ai

    ports:
      - "5433:5432"

  redis:
    image: redis:7
    container_name: qa_redis

    ports:
      - "6379:6379"
