import os
from dotenv import load_dotenv
from langchain_ollama import OllamaLLM
from langchain_openai import ChatOpenAI
from langchain_google_genai import ChatGoogleGenerativeAI
from langchain_anthropic import ChatAnthropic

load_dotenv()

def get_model_info():
    model_type = os.getenv("ACTIVE_MODEL_TYPE", "local").lower()
    if model_type == "openai":
        return os.getenv("OPENAI_MODEL", "gpt-4o")
    elif model_type == "gemini":    
        return os.getenv("GEMINI_MODEL", "gemini-flash-latest")
    elif model_type == "claude":
        return os.getenv("CLAUDE_MODEL", "claude-3-5-sonnet-20240620")
    else:
        return os.getenv("LOCAL_MODEL_NAME", "qwen3:4b")

def get_model():
    """
    Centralized factory to initialize the AI model based on .env configuration.
    """
    model_type = os.getenv("ACTIVE_MODEL_TYPE", "local").lower()
    
    if model_type == "openai":
        return ChatOpenAI(
            model=os.getenv("OPENAI_MODEL", "gpt-4o"),
            api_key=os.getenv("OPENAI_API_KEY")
        )
    
    elif model_type == "gemini":
        return ChatGoogleGenerativeAI(
            model=os.getenv("GEMINI_MODEL", "gemini-flash-latest"),
            google_api_key=os.getenv("GEMINI_API_KEY"),
            convert_system_message_to_human=True
        )
    
    elif model_type == "claude":
        return ChatAnthropic(
            model=os.getenv("CLAUDE_MODEL", "claude-3-5-sonnet-20240620"),
            anthropic_api_key=os.getenv("ANTHROPIC_API_KEY")
        )
    
    else:  # Default to Local Ollama
        return OllamaLLM(
            model=os.getenv("LOCAL_MODEL_NAME", "qwen3:4b"),
            base_url=os.getenv("OLLAMA_BASE_URL", "http://localhost:11434")
        )

# Initialize single global instances
llm = get_model()
active_model_name = get_model_info()

def extract_text(response):
    """
    Intelligently extracts the text content from various LangChain response types.
    """
    if hasattr(response, 'content'):
        return response.content
    return str(response)

def generate_response(prompt: str):
    """
    High-level helper to generate a clean string response from the active LLM.
    """
    raw_response = llm.invoke(prompt)
    clean_text = extract_text(raw_response)
    return add_ai_stamp(clean_text)

def add_ai_stamp(content: str):
    """
    Appends a dynamic stamp to the generated content.
    """
    # Ensure content is a string
    text = extract_text(content)
    stamp = f"\n\n---\n🛡️ Generated by Jira MCP/RAG Service - powered by {active_model_name}"
    return f"{text}{stamp}"
